{
 "title": "SonarQube Detail",
 "tags": [
  "sonarqube",
  "prometheus",
  "sonarqube-exporter",
  "in-progress"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "project", "label": "Project Key", "query": "label_values(sonar_bugs, key)" },
   { "name": "url", "query": "https://sonarqube.example.com" }
  ]
 },
 "panels": [
  {
   "title": "Quality Gate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_alert_status{key=\"${project:raw}\"}"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code where you will get bahavior other than what was expected. \nA: 0 bugs;\nB: at least 1 Minor bug;\nC: at least 1 Major bug;\nD: at least 1 Critical bug;\nE: at least 1 Blocker bug;",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Security",
   "type": "singlestat",
   "description": "Issues in this domain mark potential weakness to hackers. \nA: 0 vulnerabilities;\nB: at least 1 Minor vulnerability;\nC: at least 1 Major vulnerability;\nD: at least 1 Critical vulnerability;\nE: at least 1 Blocker vulnerability;",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_security_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Maintainability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code that will be more difficult to update competently than it should. Rating given to your project related to the value of Technical Debt Ratio (remediation cost / development cost)\nA: <= 5%;\nB: 6% - 10%;\nC: 11% - 20%;\nD: 21% - 50%;\nE: > 50%",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_sqale_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "description": "It's mix of Line coverage and Branch coverage. Its goal is to provide even more accurate answer to following question: How much source code has been covered by the unit tests?",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Duplication",
   "type": "singlestat",
   "description": "Duplicated line density. Formula: duplicated_line_density = duplicated_lines / total_lines * 100",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "singlestat",
   "description": "Total issues",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_violations{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "description": "Line of code:\nXS: < 1.000 LOC;\nS: 1.000 - 10.000 LOC;\nM: 10.000 - 100.000 LOC;\nL:  100.000 - 500.000 LOC;\nXL: > 500.000 LOC;",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_ncloc{key=~\"^$project$\"}"
    }
   ]
  },
  { "title": "Reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "content": "Issues in this domain mark your code where you will get bahavior other than what was expected"
  },
  {
   "title": "Bugs",
   "type": "graph",
   "description": "A bug is coding error that will break your code and needs to be fixed immediately",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "bug(s)" }
   ],
   "targets": [
    {
     "expr": "sonar_bugs{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  {
   "title": "Remediation",
   "type": "graph",
   "description": "Effort to fix all bug issues",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 4 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "sonar_reliability_remediation_effort{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "content": "Issues in this domain mark potential weakness to hackers"
  },
  {
   "title": "Security Hotspots",
   "type": "graph",
   "description": "Security-sensitive code that requires manual review to assess whether or not a vulnerability exists",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "issue(s)" }
   ],
   "targets": [
    {
     "expr": "sonar_security_hotspots{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "graph",
   "description": "Vulnerabilities are code that can be exploited by hackers",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "vulnerabilities" }
   ],
   "targets": [
    {
     "expr": "sonar_vulnerabilities{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  {
   "title": "Remediation",
   "type": "graph",
   "description": "Effort to fix all vulnerability issues",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "sonar_security_remediation_effort{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  {
   "title": "Remediation",
   "type": "graph",
   "description": "Effort to fix all vulnerability issues",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "sonar_security_remediation_effort{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  { "title": "Maintainability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "content": "Issues in this domain mark your code that will be more difficult to update competently than it should"
  },
  {
   "title": "Debt Ratio",
   "type": "graph",
   "description": "Ratio between cost to develop the software and cost to fix it. The formula is: remediation cost / (cost to develop 1 line * number of lines). The value of cost to develop 1 line is 0.06 days",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sonar_sqale_debt_ratio{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  {
   "title": "Effort to reach rating A",
   "type": "graph",
   "description": "Effort to reach maintainability rating A",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "sonar_effort_to_reach_maintainability_rating_a{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "graph",
   "description": "Code that is confusing and difficult to maintain",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "issue(s)" }
   ],
   "targets": [
    {
     "expr": "sonar_code_smells{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  {
   "title": "Technical Debt",
   "type": "graph",
   "description": "Effort to fix all code smells",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "sonar_sqale_index{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  { "title": "Coverage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Coverage",
   "type": "gauge",
   "description": "It's mix of Line coverage and Branch coverage. Its goal is to provide even more accurate answer to following question: How much source code has been covered by the unit tests?",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "graph",
   "description": "It's mix of Line coverage and Branch coverage. Its goal is to provide even more accurate answer to following question: How much source code has been covered by the unit tests?",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  {
   "title": "Line Coverage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sonar_line_coverage{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Line Coverage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sonar_line_coverage{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  {
   "title": "Branch Coverage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sonar_branch_coverage{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Branch Coverage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sonar_branch_coverage{key=~\"^$project$\"}",
     "legendFormat": " $project"
    }
   ]
  },
  {
   "title": "Unit Test Success",
   "type": "gauge",
   "description": "test_success_density = (total unit tests - test failed - test error) / total unit tests * 100",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sonar_test_success_density{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Unit Test Success",
   "type": "graph",
   "description": "test_success_density = (total unit tests - test failed - test error) / total unit tests * 100",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sonar_test_success_density{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  { "title": "Duplication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Duplicated Line Density",
   "type": "gauge",
   "description": "duplicated_line_density = duplicated_lines / total_lines * 100",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Duplicated Line Density",
   "type": "graph",
   "description": "duplicated_line_density = duplicated_lines / total_lines * 100",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"^$project$\"}",
     "legendFormat": " $project"
    }
   ]
  },
  {
   "title": "Duplicated Lines",
   "type": "graph",
   "description": "Number of lines involved in duplication",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "lines" }
   ],
   "targets": [
    {
     "expr": "sonar_duplicated_lines{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  {
   "title": "Duplicated Blocks",
   "type": "graph",
   "description": "Number of blocks of lines",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "blocks" }
   ],
   "targets": [
    {
     "expr": "sonar_duplicated_blocks{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  },
  {
   "title": "Duplicated Files",
   "type": "graph",
   "description": "Number of files involved in duplication",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "files" }
   ],
   "targets": [
    {
     "expr": "sonar_duplicated_files{key=~\"^$project$\"}",
     "legendFormat": "$project"
    }
   ]
  }
 ]
}