{
 "title": "SonarQube",
 "tags": [
  "sonarqube",
  "prometheus",
  "sonarqube-exporter",
  "in-progress",
  "ovreview"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "project", "label": "Project Key", "query": "label_values(sonar_bugs, key)" },
   { "name": "url", "query": "https://sonarqube.example.com" }
  ]
 },
 "panels": [
  { "title": "${project}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "project" },
  {
   "title": "Quality Gate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_alert_status{key=\"${project:raw}\"}"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code where you will get bahavior other than what was expected. \nA: 0 bugs;\nB: at least 1 Minor bug;\nC: at least 1 Major bug;\nD: at least 1 Critical bug;\nE: at least 1 Blocker bug;",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Security",
   "type": "singlestat",
   "description": "Issues in this domain mark potential weakness to hackers. \nA: 0 vulnerabilities;\nB: at least 1 Minor vulnerability;\nC: at least 1 Major vulnerability;\nD: at least 1 Critical vulnerability;\nE: at least 1 Blocker vulnerability;",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_security_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Maintainability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code that will be more difficult to update competently than it should. Rating given to your project related to the value of Technical Debt Ratio (remediation cost / development cost)\nA: <= 5%;\nB: 6% - 10%;\nC: 11% - 20%;\nD: 21% - 50%;\nE: > 50%",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_sqale_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "description": "It's mix of Line coverage and Branch coverage. Its goal is to provide even more accurate answer to following question: How much source code has been covered by the unit tests?",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Duplication",
   "type": "singlestat",
   "description": "Duplicated line density. Formula: duplicated_line_density = duplicated_lines / total_lines * 100",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "singlestat",
   "description": "Total issues",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_violations{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "description": "Line of code:\nXS: < 1.000 LOC;\nS: 1.000 - 10.000 LOC;\nM: 10.000 - 100.000 LOC;\nL:  100.000 - 500.000 LOC;\nXL: > 500.000 LOC;",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_ncloc{key=~\"^$project$\"}"
    }
   ]
  },
  { "title": "${project}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Quality Gate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_alert_status{key=\"${project:raw}\"}"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code where you will get bahavior other than what was expected. \nA: 0 bugs;\nB: at least 1 Minor bug;\nC: at least 1 Major bug;\nD: at least 1 Critical bug;\nE: at least 1 Blocker bug;",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Security",
   "type": "singlestat",
   "description": "Issues in this domain mark potential weakness to hackers. \nA: 0 vulnerabilities;\nB: at least 1 Minor vulnerability;\nC: at least 1 Major vulnerability;\nD: at least 1 Critical vulnerability;\nE: at least 1 Blocker vulnerability;",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_security_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Maintainability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code that will be more difficult to update competently than it should. Rating given to your project related to the value of Technical Debt Ratio (remediation cost / development cost)\nA: <= 5%;\nB: 6% - 10%;\nC: 11% - 20%;\nD: 21% - 50%;\nE: > 50%",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_sqale_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "description": "It's mix of Line coverage and Branch coverage. Its goal is to provide even more accurate answer to following question: How much source code has been covered by the unit tests?",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Duplication",
   "type": "singlestat",
   "description": "Duplicated line density. Formula: duplicated_line_density = duplicated_lines / total_lines * 100",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "singlestat",
   "description": "Total issues",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_violations{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "description": "Line of code:\nXS: < 1.000 LOC;\nS: 1.000 - 10.000 LOC;\nM: 10.000 - 100.000 LOC;\nL:  100.000 - 500.000 LOC;\nXL: > 500.000 LOC;",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_ncloc{key=~\"^$project$\"}"
    }
   ]
  },
  { "title": "${project}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Quality Gate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_alert_status{key=\"${project:raw}\"}"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code where you will get bahavior other than what was expected. \nA: 0 bugs;\nB: at least 1 Minor bug;\nC: at least 1 Major bug;\nD: at least 1 Critical bug;\nE: at least 1 Blocker bug;",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Security",
   "type": "singlestat",
   "description": "Issues in this domain mark potential weakness to hackers. \nA: 0 vulnerabilities;\nB: at least 1 Minor vulnerability;\nC: at least 1 Major vulnerability;\nD: at least 1 Critical vulnerability;\nE: at least 1 Blocker vulnerability;",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_security_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Maintainability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code that will be more difficult to update competently than it should. Rating given to your project related to the value of Technical Debt Ratio (remediation cost / development cost)\nA: <= 5%;\nB: 6% - 10%;\nC: 11% - 20%;\nD: 21% - 50%;\nE: > 50%",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_sqale_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "description": "It's mix of Line coverage and Branch coverage. Its goal is to provide even more accurate answer to following question: How much source code has been covered by the unit tests?",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Duplication",
   "type": "singlestat",
   "description": "Duplicated line density. Formula: duplicated_line_density = duplicated_lines / total_lines * 100",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "singlestat",
   "description": "Total issues",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_violations{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "description": "Line of code:\nXS: < 1.000 LOC;\nS: 1.000 - 10.000 LOC;\nM: 10.000 - 100.000 LOC;\nL:  100.000 - 500.000 LOC;\nXL: > 500.000 LOC;",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_ncloc{key=~\"^$project$\"}"
    }
   ]
  },
  { "title": "${project}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Quality Gate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_alert_status{key=\"${project:raw}\"}"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code where you will get bahavior other than what was expected. \nA: 0 bugs;\nB: at least 1 Minor bug;\nC: at least 1 Major bug;\nD: at least 1 Critical bug;\nE: at least 1 Blocker bug;",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Security",
   "type": "singlestat",
   "description": "Issues in this domain mark potential weakness to hackers. \nA: 0 vulnerabilities;\nB: at least 1 Minor vulnerability;\nC: at least 1 Major vulnerability;\nD: at least 1 Critical vulnerability;\nE: at least 1 Blocker vulnerability;",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_security_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Maintainability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code that will be more difficult to update competently than it should. Rating given to your project related to the value of Technical Debt Ratio (remediation cost / development cost)\nA: <= 5%;\nB: 6% - 10%;\nC: 11% - 20%;\nD: 21% - 50%;\nE: > 50%",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_sqale_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "description": "It's mix of Line coverage and Branch coverage. Its goal is to provide even more accurate answer to following question: How much source code has been covered by the unit tests?",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Duplication",
   "type": "singlestat",
   "description": "Duplicated line density. Formula: duplicated_line_density = duplicated_lines / total_lines * 100",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "singlestat",
   "description": "Total issues",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_violations{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "description": "Line of code:\nXS: < 1.000 LOC;\nS: 1.000 - 10.000 LOC;\nM: 10.000 - 100.000 LOC;\nL:  100.000 - 500.000 LOC;\nXL: > 500.000 LOC;",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_ncloc{key=~\"^$project$\"}"
    }
   ]
  },
  { "title": "${project}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Quality Gate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_alert_status{key=\"${project:raw}\"}"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code where you will get bahavior other than what was expected. \nA: 0 bugs;\nB: at least 1 Minor bug;\nC: at least 1 Major bug;\nD: at least 1 Critical bug;\nE: at least 1 Blocker bug;",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Security",
   "type": "singlestat",
   "description": "Issues in this domain mark potential weakness to hackers. \nA: 0 vulnerabilities;\nB: at least 1 Minor vulnerability;\nC: at least 1 Major vulnerability;\nD: at least 1 Critical vulnerability;\nE: at least 1 Blocker vulnerability;",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_security_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Maintainability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code that will be more difficult to update competently than it should. Rating given to your project related to the value of Technical Debt Ratio (remediation cost / development cost)\nA: <= 5%;\nB: 6% - 10%;\nC: 11% - 20%;\nD: 21% - 50%;\nE: > 50%",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_sqale_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "description": "It's mix of Line coverage and Branch coverage. Its goal is to provide even more accurate answer to following question: How much source code has been covered by the unit tests?",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Duplication",
   "type": "singlestat",
   "description": "Duplicated line density. Formula: duplicated_line_density = duplicated_lines / total_lines * 100",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "singlestat",
   "description": "Total issues",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_violations{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "description": "Line of code:\nXS: < 1.000 LOC;\nS: 1.000 - 10.000 LOC;\nM: 10.000 - 100.000 LOC;\nL:  100.000 - 500.000 LOC;\nXL: > 500.000 LOC;",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_ncloc{key=~\"^$project$\"}"
    }
   ]
  },
  { "title": "${project}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Quality Gate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_alert_status{key=\"${project:raw}\"}"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code where you will get bahavior other than what was expected. \nA: 0 bugs;\nB: at least 1 Minor bug;\nC: at least 1 Major bug;\nD: at least 1 Critical bug;\nE: at least 1 Blocker bug;",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Security",
   "type": "singlestat",
   "description": "Issues in this domain mark potential weakness to hackers. \nA: 0 vulnerabilities;\nB: at least 1 Minor vulnerability;\nC: at least 1 Major vulnerability;\nD: at least 1 Critical vulnerability;\nE: at least 1 Blocker vulnerability;",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_security_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Maintainability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code that will be more difficult to update competently than it should. Rating given to your project related to the value of Technical Debt Ratio (remediation cost / development cost)\nA: <= 5%;\nB: 6% - 10%;\nC: 11% - 20%;\nD: 21% - 50%;\nE: > 50%",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_sqale_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "description": "It's mix of Line coverage and Branch coverage. Its goal is to provide even more accurate answer to following question: How much source code has been covered by the unit tests?",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Duplication",
   "type": "singlestat",
   "description": "Duplicated line density. Formula: duplicated_line_density = duplicated_lines / total_lines * 100",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "singlestat",
   "description": "Total issues",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_violations{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "description": "Line of code:\nXS: < 1.000 LOC;\nS: 1.000 - 10.000 LOC;\nM: 10.000 - 100.000 LOC;\nL:  100.000 - 500.000 LOC;\nXL: > 500.000 LOC;",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_ncloc{key=~\"^$project$\"}"
    }
   ]
  },
  { "title": "${project}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Quality Gate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_alert_status{key=\"${project:raw}\"}"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code where you will get bahavior other than what was expected. \nA: 0 bugs;\nB: at least 1 Minor bug;\nC: at least 1 Major bug;\nD: at least 1 Critical bug;\nE: at least 1 Blocker bug;",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Security",
   "type": "singlestat",
   "description": "Issues in this domain mark potential weakness to hackers. \nA: 0 vulnerabilities;\nB: at least 1 Minor vulnerability;\nC: at least 1 Major vulnerability;\nD: at least 1 Critical vulnerability;\nE: at least 1 Blocker vulnerability;",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_security_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Maintainability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code that will be more difficult to update competently than it should. Rating given to your project related to the value of Technical Debt Ratio (remediation cost / development cost)\nA: <= 5%;\nB: 6% - 10%;\nC: 11% - 20%;\nD: 21% - 50%;\nE: > 50%",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_sqale_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "description": "It's mix of Line coverage and Branch coverage. Its goal is to provide even more accurate answer to following question: How much source code has been covered by the unit tests?",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 25 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Duplication",
   "type": "singlestat",
   "description": "Duplicated line density. Formula: duplicated_line_density = duplicated_lines / total_lines * 100",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 25 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "singlestat",
   "description": "Total issues",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 25 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_violations{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "description": "Line of code:\nXS: < 1.000 LOC;\nS: 1.000 - 10.000 LOC;\nM: 10.000 - 100.000 LOC;\nL:  100.000 - 500.000 LOC;\nXL: > 500.000 LOC;",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 25 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_ncloc{key=~\"^$project$\"}"
    }
   ]
  },
  { "title": "${project}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Quality Gate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_alert_status{key=\"${project:raw}\"}"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code where you will get bahavior other than what was expected. \nA: 0 bugs;\nB: at least 1 Minor bug;\nC: at least 1 Major bug;\nD: at least 1 Critical bug;\nE: at least 1 Blocker bug;",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Security",
   "type": "singlestat",
   "description": "Issues in this domain mark potential weakness to hackers. \nA: 0 vulnerabilities;\nB: at least 1 Minor vulnerability;\nC: at least 1 Major vulnerability;\nD: at least 1 Critical vulnerability;\nE: at least 1 Blocker vulnerability;",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 29 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_security_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Maintainability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code that will be more difficult to update competently than it should. Rating given to your project related to the value of Technical Debt Ratio (remediation cost / development cost)\nA: <= 5%;\nB: 6% - 10%;\nC: 11% - 20%;\nD: 21% - 50%;\nE: > 50%",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 29 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_sqale_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "description": "It's mix of Line coverage and Branch coverage. Its goal is to provide even more accurate answer to following question: How much source code has been covered by the unit tests?",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Duplication",
   "type": "singlestat",
   "description": "Duplicated line density. Formula: duplicated_line_density = duplicated_lines / total_lines * 100",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "singlestat",
   "description": "Total issues",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 29 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_violations{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "description": "Line of code:\nXS: < 1.000 LOC;\nS: 1.000 - 10.000 LOC;\nM: 10.000 - 100.000 LOC;\nL:  100.000 - 500.000 LOC;\nXL: > 500.000 LOC;",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 29 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_ncloc{key=~\"^$project$\"}"
    }
   ]
  },
  { "title": "${project}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Quality Gate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_alert_status{key=\"${project:raw}\"}"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code where you will get bahavior other than what was expected. \nA: 0 bugs;\nB: at least 1 Minor bug;\nC: at least 1 Major bug;\nD: at least 1 Critical bug;\nE: at least 1 Blocker bug;",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Security",
   "type": "singlestat",
   "description": "Issues in this domain mark potential weakness to hackers. \nA: 0 vulnerabilities;\nB: at least 1 Minor vulnerability;\nC: at least 1 Major vulnerability;\nD: at least 1 Critical vulnerability;\nE: at least 1 Blocker vulnerability;",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_security_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Maintainability",
   "type": "singlestat",
   "description": "Issues in this domain mark your code that will be more difficult to update competently than it should. Rating given to your project related to the value of Technical Debt Ratio (remediation cost / development cost)\nA: <= 5%;\nB: 6% - 10%;\nC: 11% - 20%;\nD: 21% - 50%;\nE: > 50%",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonar_sqale_rating{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "singlestat",
   "description": "It's mix of Line coverage and Branch coverage. Its goal is to provide even more accurate answer to following question: How much source code has been covered by the unit tests?",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 33 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Duplication",
   "type": "singlestat",
   "description": "Duplicated line density. Formula: duplicated_line_density = duplicated_lines / total_lines * 100",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 33 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "singlestat",
   "description": "Total issues",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_violations{key=~\"^$project$\"}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "description": "Line of code:\nXS: < 1.000 LOC;\nS: 1.000 - 10.000 LOC;\nM: 10.000 - 100.000 LOC;\nL:  100.000 - 500.000 LOC;\nXL: > 500.000 LOC;",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonar_ncloc{key=~\"^$project$\"}"
    }
   ]
  }
 ]
}